name: C# Lint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Run C# Linter
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Codigo/App_1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore *.csproj || true

      - name: Build (ignore warnings)
        run: dotnet build *.csproj --no-restore || true

      - name: Run format check (ignore warnings)
        run: dotnet format *.csproj --verify-no-changes --severity warn || true

      - name: Run tests (optional)
        run: dotnet test *.csproj --no-build --verbosity normal || true
